@startuml
class Config.ConexionMySQL
class Controlador.ControladorCategoria
class Controlador.ControladorCliente
class Controlador.ControladorPerfil
class Controlador.ControladorProducto
class Controlador.ControladorTrabajador
class Controlador.controladorValidar
class Controlador.controladorVistasCliente
class Modelo.Categoria
class Modelo.Cliente
class Modelo.Empleado
class Modelo.Md5
class Modelo.Menu
class Modelo.MenuPerfil
class Modelo.Pedido
class Modelo.Perfil
class Modelo.Producto
class Modelo.Usuario
class Modelo.probandoDiccionarios
class ModeloDAO.ListaProductosGeneralById
class ModeloDAO.ObtenerUsuarioMaximo
class ModeloDAO.PerfilAsignarMenuDAO
class ModeloDAO.PerfilEditarDAO
class ModeloDAO.ValidarMenuDAO
class ModeloDAO.ValidarUsuario
class ModeloDAO.actualizarPerfil
class ModeloDAO.actualizarProducto
class ModeloDAO.agregarCategoria
class ModeloDAO.agregarClienteActivar
class ModeloDAO.agregarPerfil
class ModeloDAO.agregarProducto
class ModeloDAO.agregarUsuarioActivarCuenta
class ModeloDAO.buscarCategoria
class ModeloDAO.buscarProductoAdmin
class ModeloDAO.categoriaListarAdmin
class ModeloDAO.deshabilitarPerfil
class ModeloDAO.editarCategoria
class ModeloDAO.eliminarCategoria
class ModeloDAO.eliminarProducto
class ModeloDAO.filtrarPerfil
class ModeloDAO.habilitarPerfil
class ModeloDAO.listarCategoriaPorID
class ModeloDAO.listarMenu
class ModeloDAO.listarPerfilId
class ModeloDAO.listarUsuariosRoles
class ModeloDAO.mostrarCategoria
class ModeloDAO.mostrarProducto
class ModeloDAO.ocultarCategoria
class ModeloDAO.ocultarProducto
class ModeloDAO.perfilEliminar
class ModeloDAO.productoListarById
class ModeloDAO.productosListarAdmin
class ModeloDAO.revisarDatosRegistro
class com.google.gson.Gson
class java.io.IOException
class java.io.PrintWriter
class java.security.MessageDigest
class java.sql.CallableStatement
class java.sql.Connection
class java.sql.DriverManager
class java.sql.ResultSet
class java.sql.Types
class java.util.ArrayList
class java.util.Arrays
class java.util.HashMap
class java.util.List
class java.util.Map
class java.util.Properties
class javax.activation.DataHandler
class javax.activation.FileDataSource
class javax.crypto.Cipher
class javax.crypto.SecretKey
class javax.crypto.spec.SecretKeySpec
class javax.mail.BodyPart
class javax.mail.Message
class javax.mail.Session
class javax.mail.Transport
class javax.mail.internet.InternetAddress
class javax.mail.internet.MimeBodyPart
class javax.mail.internet.MimeMessage
class javax.mail.internet.MimeMultipart
class javax.servlet.ServletException
class javax.servlet.http.HttpServlet
class javax.servlet.http.HttpServletRequest
class javax.servlet.http.HttpServletResponse
class javax.servlet.http.HttpSession
class org.apache.commons.codec.binary.Base64
@enduml